apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2
        image: my-app-image
        resources:
              requests:
                cpu: "2000m"
                memory: "2Gi"
        ports:
          - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP